required = [
  "k8s.io/code-generator/cmd/client-gen",
  # needed by generated clientsets, but not an explicit dep in client-gen itself
  "k8s.io/apimachinery/pkg/apimachinery/registered",

  "k8s.io/code-generator/cmd/deepcopy-gen",
  "k8s.io/code-generator/cmd/defaulter-gen",
  "k8s.io/code-generator/cmd/lister-gen",
  "k8s.io/code-generator/cmd/informer-gen",
]

[[constraint]]
  name="k8s.io/client-go"
  branch="release-6.0"

[[constraint]]
  name="k8s.io/api"
  branch="release-1.9"

[[constraint]]
  name="k8s.io/apimachinery"
  branch="release-1.9"

[[constraint]]
  name = "k8s.io/code-generator"
  version = "kubernetes-1.9.0"

[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "^1.0.4"
