[[constraint]]
  name="k8s.io/client-go"
  version="v7.0.0"

[[constraint]]
  name="k8s.io/api"
  branch="release-1.10"

[[constraint]]
  name="k8s.io/apimachinery"
  branch="release-1.10"

[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "^1.0.5"

[[constraint]]
  name = "google.golang.org/grpc"
  version = "=v1.10.0"
