[[constraint]]
  name="k8s.io/client-go"
  branch="release-6.0"

[[constraint]]
  name="k8s.io/api"
  branch="release-1.9"

[[constraint]]
  name="google.golang.org/grpc"
  version="~1.8"

[[constraint]]
  name="k8s.io/apimachinery"
  branch="release-1.9"
