---
apiVersion: contour.heptio.com/v1beta1
kind: IngressRoute
metadata: 
  name: basic
  namespace: default
spec: 
  virtualhost:
    fqdn: foo-basic.bar.com
  routes: 
    - match: /
      services: 
        - name: s1
          port: 80
---
# apiVersion: extensions/v1beta1
# kind: Ingress
# metadata:
#   name: basic
# spec:
#   rules:
#   - host: foo-basic.bar.com
#     http:
#       paths:
#       - backend:
#           serviceName: s1
#           servicePort: 80
