---
apiVersion: contour.heptio.com/v1beta1
kind: IngressRoute
metadata: 
  name: health-check
  namespace: default
spec:
  virtualhost:
    fqdn: health.bar.com
  healthCheck:
    path: /healthy
    intervalSeconds: 5
    timeoutSeconds: 2
    unhealthyThresholdCount: 3
    healthyThresholdCount: 5
  routes: 
    - match: /
      services: 
        - name: s1-def-health
          port: 80
        - name: s2-def-health
          port: 80
