---
apiVersion: contour.heptio.com/v1beta1
kind: IngressRoute
metadata: 
  name: domain-aliases
  namespace: default
spec: 
  virtualhost:
    fqdn: bar.com
  routes: 
    - match: /
      services: 
        - name: s1
          port: 80
