---
apiVersion: contour.heptio.com/v1beta1
kind: IngressRoute
metadata: 
  name: weight-shifting
  namespace: default
spec: 
  virtualhost:
    fqdn: weights.bar.com
  routes: 
    - match: /
      services: 
        - name: s1
          port: 80
          weight: 10
        - name: s2
          port: 80
          weight: 90
